# Generated by Django 6.0 on 2025-12-28 02:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("warrior", "Воин"),
                            ("paladin", "Паладин"),
                            ("hunter", "Охотник"),
                            ("rogue", "Разбойник"),
                            ("priest", "Жрец"),
                            ("death_knight", "Рыцарь смерти"),
                            ("shaman", "Шаман"),
                            ("mage", "Маг"),
                            ("warlock", "Чернокнижник"),
                            ("monk", "Монах"),
                            ("druid", "Друид"),
                            ("demon_hunter", "Охотник на демонов"),
                            ("evoker", "Пробудитель"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Класс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Класс",
                "verbose_name_plural": "Классы",
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Специализация")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("tank", "Танк"),
                            ("healer", "Хилер"),
                            ("melee", "Ближний бой"),
                            ("ranged", "Дальний бой"),
                        ],
                        max_length=10,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="characters.characterclass",
                        verbose_name="Класс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Специализация",
                "verbose_name_plural": "Специализации",
                "unique_together": {("character_class", "name")},
            },
        ),
        migrations.CreateModel(
            name="UserCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="2-16 символов",
                        max_length=16,
                        verbose_name="Имя персонажа",
                    ),
                ),
                (
                    "item_level",
                    models.IntegerField(
                        default=600,
                        validators=[django.core.validators.MinValueValidator(600)],
                        verbose_name="Уровень предметов",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, verbose_name="Основной персонаж"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="characters",
                        to="characters.specialization",
                        verbose_name="Специализация",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персонаж",
                "verbose_name_plural": "Персонажи",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_main", True)),
                        fields=("user",),
                        name="unique_main_character_per_user",
                    )
                ],
                "unique_together": {("name", "user")},
            },
        ),
    ]
